# Generated by Django 4.2.1 on 2023-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='手机号码'),
        ),
    ]
